// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.3
// source: proto/scheduler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerService_SchedulerOverview_FullMethodName             = "/scheduler.SchedulerService/SchedulerOverview"
	SchedulerService_SchedulerListJobs_FullMethodName             = "/scheduler.SchedulerService/SchedulerListJobs"
	SchedulerService_SchedulerGetJob_FullMethodName               = "/scheduler.SchedulerService/SchedulerGetJob"
	SchedulerService_SchedulerCreateJob_FullMethodName            = "/scheduler.SchedulerService/SchedulerCreateJob"
	SchedulerService_SchedulerUpdateJob_FullMethodName            = "/scheduler.SchedulerService/SchedulerUpdateJob"
	SchedulerService_SchedulerDeleteJob_FullMethodName            = "/scheduler.SchedulerService/SchedulerDeleteJob"
	SchedulerService_SchedulerPauseJob_FullMethodName             = "/scheduler.SchedulerService/SchedulerPauseJob"
	SchedulerService_SchedulerResumeJob_FullMethodName            = "/scheduler.SchedulerService/SchedulerResumeJob"
	SchedulerService_SchedulerTriggerJob_FullMethodName           = "/scheduler.SchedulerService/SchedulerTriggerJob"
	SchedulerService_SchedulerListExecutions_FullMethodName       = "/scheduler.SchedulerService/SchedulerListExecutions"
	SchedulerService_SchedulerGetExecution_FullMethodName         = "/scheduler.SchedulerService/SchedulerGetExecution"
	SchedulerService_SchedulerAbortExecution_FullMethodName       = "/scheduler.SchedulerService/SchedulerAbortExecution"
	SchedulerService_SchedulerRetryExecution_FullMethodName       = "/scheduler.SchedulerService/SchedulerRetryExecution"
	SchedulerService_SchedulerGetThrottleConfig_FullMethodName    = "/scheduler.SchedulerService/SchedulerGetThrottleConfig"
	SchedulerService_SchedulerUpdateThrottleConfig_FullMethodName = "/scheduler.SchedulerService/SchedulerUpdateThrottleConfig"
)

// SchedulerServiceClient is the client API for SchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 调度器服务
// [EN] Scheduler Service
type SchedulerServiceClient interface {
	// 调度器概览
	// [EN] Scheduler overview
	SchedulerOverview(ctx context.Context, in *SchedulerOverviewRequest, opts ...grpc.CallOption) (*SchedulerOverviewResponse, error)
	// 列出任务
	// [EN] List jobs
	SchedulerListJobs(ctx context.Context, in *SchedulerListJobsRequest, opts ...grpc.CallOption) (*SchedulerListJobsResponse, error)
	// 获取任务详情
	// [EN] Get job detail
	SchedulerGetJob(ctx context.Context, in *SchedulerGetJobRequest, opts ...grpc.CallOption) (*SchedulerGetJobResponse, error)
	// 创建任务
	// [EN] Create job
	SchedulerCreateJob(ctx context.Context, in *SchedulerCreateJobRequest, opts ...grpc.CallOption) (*SchedulerCreateJobResponse, error)
	// 更新任务
	// [EN] Update job
	SchedulerUpdateJob(ctx context.Context, in *SchedulerUpdateJobRequest, opts ...grpc.CallOption) (*SchedulerUpdateJobResponse, error)
	// 删除任务
	// [EN] Delete job
	SchedulerDeleteJob(ctx context.Context, in *SchedulerDeleteJobRequest, opts ...grpc.CallOption) (*SchedulerDeleteJobResponse, error)
	// 暂停任务
	// [EN] Pause job
	SchedulerPauseJob(ctx context.Context, in *SchedulerPauseJobRequest, opts ...grpc.CallOption) (*SchedulerPauseJobResponse, error)
	// 恢复任务
	// [EN] Resume job
	SchedulerResumeJob(ctx context.Context, in *SchedulerResumeJobRequest, opts ...grpc.CallOption) (*SchedulerResumeJobResponse, error)
	// 手动触发任务
	// [EN] Manual trigger job
	SchedulerTriggerJob(ctx context.Context, in *SchedulerTriggerJobRequest, opts ...grpc.CallOption) (*SchedulerTriggerJobResponse, error)
	// 列出执行记录
	// [EN] List executions
	SchedulerListExecutions(ctx context.Context, in *SchedulerListExecutionsRequest, opts ...grpc.CallOption) (*SchedulerListExecutionsResponse, error)
	// 获取执行详情
	// [EN] Get execution detail
	SchedulerGetExecution(ctx context.Context, in *SchedulerGetExecutionRequest, opts ...grpc.CallOption) (*SchedulerGetExecutionResponse, error)
	// 中止执行
	// [EN] Abort execution
	SchedulerAbortExecution(ctx context.Context, in *SchedulerAbortExecutionRequest, opts ...grpc.CallOption) (*SchedulerAbortExecutionResponse, error)
	// 重试执行
	// [EN] Retry execution
	SchedulerRetryExecution(ctx context.Context, in *SchedulerRetryExecutionRequest, opts ...grpc.CallOption) (*SchedulerRetryExecutionResponse, error)
	// 获取节流配置
	// [EN] Get throttle config
	SchedulerGetThrottleConfig(ctx context.Context, in *SchedulerGetThrottleConfigRequest, opts ...grpc.CallOption) (*SchedulerGetThrottleConfigResponse, error)
	// 更新节流配置
	// [EN] Update throttle config
	SchedulerUpdateThrottleConfig(ctx context.Context, in *SchedulerUpdateThrottleConfigRequest, opts ...grpc.CallOption) (*SchedulerUpdateThrottleConfigResponse, error)
}

type schedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerServiceClient(cc grpc.ClientConnInterface) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) SchedulerOverview(ctx context.Context, in *SchedulerOverviewRequest, opts ...grpc.CallOption) (*SchedulerOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerOverviewResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerListJobs(ctx context.Context, in *SchedulerListJobsRequest, opts ...grpc.CallOption) (*SchedulerListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerListJobsResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerGetJob(ctx context.Context, in *SchedulerGetJobRequest, opts ...grpc.CallOption) (*SchedulerGetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerGetJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerGetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerCreateJob(ctx context.Context, in *SchedulerCreateJobRequest, opts ...grpc.CallOption) (*SchedulerCreateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerCreateJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerCreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerUpdateJob(ctx context.Context, in *SchedulerUpdateJobRequest, opts ...grpc.CallOption) (*SchedulerUpdateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerUpdateJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerUpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerDeleteJob(ctx context.Context, in *SchedulerDeleteJobRequest, opts ...grpc.CallOption) (*SchedulerDeleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerDeleteJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerDeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerPauseJob(ctx context.Context, in *SchedulerPauseJobRequest, opts ...grpc.CallOption) (*SchedulerPauseJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerPauseJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerPauseJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerResumeJob(ctx context.Context, in *SchedulerResumeJobRequest, opts ...grpc.CallOption) (*SchedulerResumeJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerResumeJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerResumeJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerTriggerJob(ctx context.Context, in *SchedulerTriggerJobRequest, opts ...grpc.CallOption) (*SchedulerTriggerJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerTriggerJobResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerTriggerJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerListExecutions(ctx context.Context, in *SchedulerListExecutionsRequest, opts ...grpc.CallOption) (*SchedulerListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerListExecutionsResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerGetExecution(ctx context.Context, in *SchedulerGetExecutionRequest, opts ...grpc.CallOption) (*SchedulerGetExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerGetExecutionResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerGetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerAbortExecution(ctx context.Context, in *SchedulerAbortExecutionRequest, opts ...grpc.CallOption) (*SchedulerAbortExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerAbortExecutionResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerAbortExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerRetryExecution(ctx context.Context, in *SchedulerRetryExecutionRequest, opts ...grpc.CallOption) (*SchedulerRetryExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerRetryExecutionResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerRetryExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerGetThrottleConfig(ctx context.Context, in *SchedulerGetThrottleConfigRequest, opts ...grpc.CallOption) (*SchedulerGetThrottleConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerGetThrottleConfigResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerGetThrottleConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) SchedulerUpdateThrottleConfig(ctx context.Context, in *SchedulerUpdateThrottleConfigRequest, opts ...grpc.CallOption) (*SchedulerUpdateThrottleConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulerUpdateThrottleConfigResponse)
	err := c.cc.Invoke(ctx, SchedulerService_SchedulerUpdateThrottleConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServiceServer is the server API for SchedulerService service.
// All implementations must embed UnimplementedSchedulerServiceServer
// for forward compatibility.
//
// 调度器服务
// [EN] Scheduler Service
type SchedulerServiceServer interface {
	// 调度器概览
	// [EN] Scheduler overview
	SchedulerOverview(context.Context, *SchedulerOverviewRequest) (*SchedulerOverviewResponse, error)
	// 列出任务
	// [EN] List jobs
	SchedulerListJobs(context.Context, *SchedulerListJobsRequest) (*SchedulerListJobsResponse, error)
	// 获取任务详情
	// [EN] Get job detail
	SchedulerGetJob(context.Context, *SchedulerGetJobRequest) (*SchedulerGetJobResponse, error)
	// 创建任务
	// [EN] Create job
	SchedulerCreateJob(context.Context, *SchedulerCreateJobRequest) (*SchedulerCreateJobResponse, error)
	// 更新任务
	// [EN] Update job
	SchedulerUpdateJob(context.Context, *SchedulerUpdateJobRequest) (*SchedulerUpdateJobResponse, error)
	// 删除任务
	// [EN] Delete job
	SchedulerDeleteJob(context.Context, *SchedulerDeleteJobRequest) (*SchedulerDeleteJobResponse, error)
	// 暂停任务
	// [EN] Pause job
	SchedulerPauseJob(context.Context, *SchedulerPauseJobRequest) (*SchedulerPauseJobResponse, error)
	// 恢复任务
	// [EN] Resume job
	SchedulerResumeJob(context.Context, *SchedulerResumeJobRequest) (*SchedulerResumeJobResponse, error)
	// 手动触发任务
	// [EN] Manual trigger job
	SchedulerTriggerJob(context.Context, *SchedulerTriggerJobRequest) (*SchedulerTriggerJobResponse, error)
	// 列出执行记录
	// [EN] List executions
	SchedulerListExecutions(context.Context, *SchedulerListExecutionsRequest) (*SchedulerListExecutionsResponse, error)
	// 获取执行详情
	// [EN] Get execution detail
	SchedulerGetExecution(context.Context, *SchedulerGetExecutionRequest) (*SchedulerGetExecutionResponse, error)
	// 中止执行
	// [EN] Abort execution
	SchedulerAbortExecution(context.Context, *SchedulerAbortExecutionRequest) (*SchedulerAbortExecutionResponse, error)
	// 重试执行
	// [EN] Retry execution
	SchedulerRetryExecution(context.Context, *SchedulerRetryExecutionRequest) (*SchedulerRetryExecutionResponse, error)
	// 获取节流配置
	// [EN] Get throttle config
	SchedulerGetThrottleConfig(context.Context, *SchedulerGetThrottleConfigRequest) (*SchedulerGetThrottleConfigResponse, error)
	// 更新节流配置
	// [EN] Update throttle config
	SchedulerUpdateThrottleConfig(context.Context, *SchedulerUpdateThrottleConfigRequest) (*SchedulerUpdateThrottleConfigResponse, error)
	mustEmbedUnimplementedSchedulerServiceServer()
}

// UnimplementedSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServiceServer struct{}

func (UnimplementedSchedulerServiceServer) SchedulerOverview(context.Context, *SchedulerOverviewRequest) (*SchedulerOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerOverview not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerListJobs(context.Context, *SchedulerListJobsRequest) (*SchedulerListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerListJobs not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerGetJob(context.Context, *SchedulerGetJobRequest) (*SchedulerGetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerGetJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerCreateJob(context.Context, *SchedulerCreateJobRequest) (*SchedulerCreateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerCreateJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerUpdateJob(context.Context, *SchedulerUpdateJobRequest) (*SchedulerUpdateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerUpdateJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerDeleteJob(context.Context, *SchedulerDeleteJobRequest) (*SchedulerDeleteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerDeleteJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerPauseJob(context.Context, *SchedulerPauseJobRequest) (*SchedulerPauseJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerPauseJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerResumeJob(context.Context, *SchedulerResumeJobRequest) (*SchedulerResumeJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerResumeJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerTriggerJob(context.Context, *SchedulerTriggerJobRequest) (*SchedulerTriggerJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerTriggerJob not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerListExecutions(context.Context, *SchedulerListExecutionsRequest) (*SchedulerListExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerListExecutions not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerGetExecution(context.Context, *SchedulerGetExecutionRequest) (*SchedulerGetExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerGetExecution not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerAbortExecution(context.Context, *SchedulerAbortExecutionRequest) (*SchedulerAbortExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerAbortExecution not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerRetryExecution(context.Context, *SchedulerRetryExecutionRequest) (*SchedulerRetryExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerRetryExecution not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerGetThrottleConfig(context.Context, *SchedulerGetThrottleConfigRequest) (*SchedulerGetThrottleConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerGetThrottleConfig not implemented")
}
func (UnimplementedSchedulerServiceServer) SchedulerUpdateThrottleConfig(context.Context, *SchedulerUpdateThrottleConfigRequest) (*SchedulerUpdateThrottleConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchedulerUpdateThrottleConfig not implemented")
}
func (UnimplementedSchedulerServiceServer) mustEmbedUnimplementedSchedulerServiceServer() {}
func (UnimplementedSchedulerServiceServer) testEmbeddedByValue()                          {}

// UnsafeSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServiceServer will
// result in compilation errors.
type UnsafeSchedulerServiceServer interface {
	mustEmbedUnimplementedSchedulerServiceServer()
}

func RegisterSchedulerServiceServer(s grpc.ServiceRegistrar, srv SchedulerServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerService_ServiceDesc, srv)
}

func _SchedulerService_SchedulerOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerOverview(ctx, req.(*SchedulerOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerListJobs(ctx, req.(*SchedulerListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerGetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerGetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerGetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerGetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerGetJob(ctx, req.(*SchedulerGetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerCreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerCreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerCreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerCreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerCreateJob(ctx, req.(*SchedulerCreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerUpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerUpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerUpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerUpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerUpdateJob(ctx, req.(*SchedulerUpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerDeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerDeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerDeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerDeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerDeleteJob(ctx, req.(*SchedulerDeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerPauseJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerPauseJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerPauseJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerPauseJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerPauseJob(ctx, req.(*SchedulerPauseJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerResumeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerResumeJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerResumeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerResumeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerResumeJob(ctx, req.(*SchedulerResumeJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerTriggerJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerTriggerJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerTriggerJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerTriggerJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerTriggerJob(ctx, req.(*SchedulerTriggerJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerListExecutions(ctx, req.(*SchedulerListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerGetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerGetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerGetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerGetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerGetExecution(ctx, req.(*SchedulerGetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerAbortExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerAbortExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerAbortExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerAbortExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerAbortExecution(ctx, req.(*SchedulerAbortExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerRetryExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerRetryExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerRetryExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerRetryExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerRetryExecution(ctx, req.(*SchedulerRetryExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerGetThrottleConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerGetThrottleConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerGetThrottleConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerGetThrottleConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerGetThrottleConfig(ctx, req.(*SchedulerGetThrottleConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_SchedulerUpdateThrottleConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulerUpdateThrottleConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).SchedulerUpdateThrottleConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_SchedulerUpdateThrottleConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).SchedulerUpdateThrottleConfig(ctx, req.(*SchedulerUpdateThrottleConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerService_ServiceDesc is the grpc.ServiceDesc for SchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SchedulerOverview",
			Handler:    _SchedulerService_SchedulerOverview_Handler,
		},
		{
			MethodName: "SchedulerListJobs",
			Handler:    _SchedulerService_SchedulerListJobs_Handler,
		},
		{
			MethodName: "SchedulerGetJob",
			Handler:    _SchedulerService_SchedulerGetJob_Handler,
		},
		{
			MethodName: "SchedulerCreateJob",
			Handler:    _SchedulerService_SchedulerCreateJob_Handler,
		},
		{
			MethodName: "SchedulerUpdateJob",
			Handler:    _SchedulerService_SchedulerUpdateJob_Handler,
		},
		{
			MethodName: "SchedulerDeleteJob",
			Handler:    _SchedulerService_SchedulerDeleteJob_Handler,
		},
		{
			MethodName: "SchedulerPauseJob",
			Handler:    _SchedulerService_SchedulerPauseJob_Handler,
		},
		{
			MethodName: "SchedulerResumeJob",
			Handler:    _SchedulerService_SchedulerResumeJob_Handler,
		},
		{
			MethodName: "SchedulerTriggerJob",
			Handler:    _SchedulerService_SchedulerTriggerJob_Handler,
		},
		{
			MethodName: "SchedulerListExecutions",
			Handler:    _SchedulerService_SchedulerListExecutions_Handler,
		},
		{
			MethodName: "SchedulerGetExecution",
			Handler:    _SchedulerService_SchedulerGetExecution_Handler,
		},
		{
			MethodName: "SchedulerAbortExecution",
			Handler:    _SchedulerService_SchedulerAbortExecution_Handler,
		},
		{
			MethodName: "SchedulerRetryExecution",
			Handler:    _SchedulerService_SchedulerRetryExecution_Handler,
		},
		{
			MethodName: "SchedulerGetThrottleConfig",
			Handler:    _SchedulerService_SchedulerGetThrottleConfig_Handler,
		},
		{
			MethodName: "SchedulerUpdateThrottleConfig",
			Handler:    _SchedulerService_SchedulerUpdateThrottleConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scheduler.proto",
}
